### ISSUE TITLE
Implement SQLAlchemy bindings

### ISSUE THREAD

**Issue by commandtab** [mirumee/ariadne#115]
Possibly related to #91, I'd love to see what an implementation of SQLAlchemy bindings might look like. Or perhaps bindings isn't the right term — I'm thinking of how [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy) works. Should I be doing this model<->resolver mapping myself?

Thank you!

**Comment by rafalp** [comment]
Tricky question. ;)

When we say "Django/Starlette" bindings, we think primarily of boilerplate that lets you add GraphQL view/controller for query execution, playground or maybe few extra utils for pagination, mutations and such.

SQLAlchemy is DBAL/ORM. graphene-sqlalchemy makes a lot of sense here, because Graphene generates GraphQL types and schema on initialization. They can introspect your models and generate types from them. They are doing same thing in graphene-django where they introspect Django's models for same result.

In Ariadne this is different, because shape of schema is decided by developer, and library only parses it and binds python functions to it. So I don't see what we could provide here? Abstractions for connections/mutations feel like very little.

I'll label this as decision needed/question and let this hang around for a while to let people discuss this.

**Comment by patrys** [comment]
If you only care about having access to a database (and not magically adapting the schema to contain all tables) you can take a look at how https://github.com/patrys/starlette-ariadne uses GINO.

**Comment by commandtab** [comment]
Ah, so "bindings" is less about data fetching, and more about integration with the Django Channels and Starlette ASGI-compatible frameworks?

**Comment by patrys** [comment]
With ASGI app merged any ASGI framework should work out of the box.

**Comment by rafalp** [comment]
We've changed semantics for "integration", so we have Starlette integration, Flask integration, etc. ect.

As for integration with ORM, this should live in resolvers layer, and writing project that autogenerates Ariadne GraphQL API from SQLAlchemy tables may be fun project for somebody, but I feel thats out of scope for us. If you want to feed your API with data from SQLAlchemy (or any such tech), run your queries in resolvers - they are made for this purpose ;)
