### ISSUE TITLE
Disable GraphQL schema introspection

### ISSUE THREAD

**Issue by benwis** [mirumee/ariadne#241]
Is there a way to disable the GraphiQL view? I couldn't find one in the docs and I'd like to not use it in production.

**Comment by levrik** [comment]
Seems to be hard-coded: https://github.com/mirumee/ariadne/blob/cbd9a2fd99791e3e4bdae80b3073b158b164cdd2/ariadne/asgi.py#L123

**Comment by rafalp** [comment]
We've considered disabling GraphQL Playground on `GET` requests but decided that feeling of secrecy this would give to people building APIs would be _false_ and hurtful in the longer run.

The secret sauce for "spying" on your API is part of GraphQL server itself, not the API explorer. If you disable playground on your server, I will still be able to use desktop GraphQL explorer like Insomnia (or just stand-alone Playground package), enter your GraphQL's URL into it, and the server will still spill the beans about available types/fields because its part of the GraphQL spec that servers can be introspected.

**Comment by rafalp** [comment]
In order to achieve proper "obscurity", one would have to put entire `/graphql/` path behind authentication and enforce that authentication on a higher level, or also implement custom resolvers for `__Schema`, `__Type`, `__TypeKind`, `__Field`, `__InputValue`, `__EnumValue`, and `__Directive` fields.

**Comment by patrys** [comment]
Yes, I think a proper solution would be an `introspection=False` flag that would disable `Query.__schema`, `Query.__type` and the playground UI.

**Comment by rafalp** [comment]
Marking this as enchancement/help wanted.

I think this could be useful for folk building public-facing API's doing some special stuff, but its not priority for us.

**Comment by thebenwaters** [comment]
@rafalp I did some initial work on just disabling the playground, but not introspection itself
#315

**Comment by markedwards** [comment]
It should be possible to disable the playground in production.  The GraphQL docs even point this out: https://graphql.org/learn/serving-over-http/#graphiql

I'd be happy to make a PR to add the capability.

**Comment by patrys** [comment]
@markedwards It's a pointless exercise to disable it unless you can also disable the introspection as both GraphiQL and Playground have their desktop variants that will happily connect to your API even if you choose not to render Playground for `GET` requests.

**Comment by markedwards** [comment]
@patrys I can see the logic of also disabling introspection overall and not just the playground, I'm not arguing against that.  Just pointing out that there is a general expectation that a GraphQL service does not make the playground available in production.

**Comment by rafalp** [comment]
One argument I've had recently for just disabling the playground was that it's a dev-tool available under the production domain and the business didn't want that. Access via local Playground installation or introspection was no further concern.

More people will likely run into such requirements so I think that's a valid case for introducing `enable_playground: bool = True` option to our ASGI/WSGI apps. We will still need to provide documentation explaining that this provides no real security gains, but the use case is here.

**Comment by rafalp** [comment]
Closing, this is already doable via `introspection` flag on `GraphQL` app.
