### ISSUE TITLE
Drop Python 3.5

### ISSUE THREAD

**Issue by salwator** [mirumee/ariadne#31]
Due to lack of support for [variable type annotations](https://www.python.org/dev/peps/pep-0526/) I suggest to drop support for Python 3.5. This is already a problem in #30 in which either code or mypy is failing and only solution is to remove hints.

We might consider testing ariadne on 3.7 for future-proofing our project.

**Comment by hugovk** [comment]
To test Python 3.7 on Travis CI, a little workaround is needed: https://github.com/travis-ci/travis-ci/issues/9815.

**Comment by rafalp** [comment]
Based on feedback we are getting, the strongest argument for dropping 3.5 would be moving to [GraphQL-Core-Next](https://github.com/graphql-python/graphql-core-next), thus letting folk experiment with async resolvers.

Originally we've started out with py3.5 because we were eyeing possible use in the Saleor and they have 3.5 on supported python versions list, but I've discussed this with @maarcingebala recently and Saleor will stick to Graphene for some time now, so we can cross this off the concerns list.

The next core was still work in progress back when we were making a push for query execution milestone, but now that its out, we could hop to it. Only gotcha here is that we'll have to create a shallow fork that namespaces it to `graphql_next` to support projects that will want to try it out side by side to GraphQL.
