### ISSUE TITLE
Allow and merge multiple mutation types

### ISSUE THREAD

**Issue by miracle2k** [mirumee/ariadne#312]
I was porting from Graphene to Ariadne, and in Graphene, my Mutations are spread across multiple files. I expected Ariadne to allow me to define multiple `type Mutation` as well (and smartly merge them), but this is not the case:

```
File "/Users/michael/Library/Caches/pypoetry/virtualenvs/dbserver-k0bMYWkt-py3.7/lib/python3.7/site-packages/graphql/validation/validate.py", line 106, in assert_valid_sdl
    raise TypeError("\n\n".join(error.message for error in errors))
TypeError: There can be only one type named 'Mutation'.
```

Possibly solved by #306.

**Comment by rafalp** [comment]
You can define single `type Mutation`, but you can also extend it via `extend type Mutation` to add more mutations in separate GraphQL files:

eg. `mutations.graphql`

```
type Mutation {
    someMutation(): Bool
}
```

eg. `user_mutations.graphql`

```
extend type Mutation {
    login(): User
}
```

**Comment by rafalp** [comment]
Marking this as `wontfix` because multiple types sharing name is against GraphQL spec. Like you've mentioned there's GraphQL modules proposal being tracked in #306 and its something we want to deliver sometime in the future, but in meantime you'll have to decide which mutation will have honor of being defined as `type Mutation` and use `extend` for the rest ;)

**Comment by miracle2k** [comment]
Thank you, that helped a lot!
