### ISSUE TITLE
Documentation on resolvers doesn't clarify where obj.first_name comes from

### ISSUE THREAD

**Issue by mnieber** [mirumee/ariadne#367]
Hi, I'm reading the docs about resolvers (https://ariadnegraphql.org/docs/resolvers) and got stuck in the explanation of `def resolve_username(obj, _*)`.  As explained in the docs, `obj is a value returned by a parent resolver`. In this case, the parent of the `username` field would be the `User` type, but this type does not have `first_name` or `last_name`. Or am I missing something? Could the example be made more complete so that you can see where `first_name` and `last_name` come from?

**Comment by rafalp** [comment]
Hi @mnieber 

Resolvers are a layer that converts your server-site data to shape described by the schema. This means that `obj` in `resolve_username(obj, *_)` can be any Python object that has `first_name` and `last_name` attributes. The schema doesn't care about how users are represented in your backend implementation. It only cares that for a user it's possible to retrieve their `username`, and resolver does this by concatenating object's attributes together.

But I agree that this example can confuse people, as it introduces a concept outside of problem that example aims to illustrate how to set resolvers for fields that belong to types other than `Query`.

**Comment by mnieber** [comment]
Hi @rafalp, thanks, I think I understand your point: there will be a separate "user resolver" for the parent, and - somehow - the result of that resolver is handed to the username resolved. But why the given example would have the effect that a user object (the one mentioned in Query?) is passed to resolve_username escapes me, so I feel my understanding is still only marginal. I'm sure it will become clear as I keep reading (and then maybe I can give a suggestion for improving the example).

`

**Comment by rafalp** [comment]
> But why the given example would have the effect that a user object (the one mentioned in Query?) is passed to resolve_username escapes me, so I feel my understanding is still only marginal.

@mnieber this is how GraphQL works. Client calls for fields like this:

```
query {
  user {
    username
  }
}
```

And GraphQL knows that it has to call `resolve_user` because the client asked for `user` field that belongs to `Query` type. Because field `user` returns `User` type (and not scalar type like `String` or `Int`), it now expects client to specify which fields of `User` it wants. In this query the only field requested is `username`. So it runs `resolve_username` function because thats the resolver associated with `username` field of `User` GraphQL type. Because this field is "child field" of `user` field, its get called with result of its resolver.

Our documentation tries to introduce GraphQL elements, but the focus is to show how those elements can be realized using Ariadne. If you wish to learn more theory about GraphQL itself, you should see [official guide](https://graphql.org/learn/). :)

**Comment by mnieber** [comment]
Yes, I think this shows a gap in my understanding of GraphQL (even though I have some experience with using graphene). When I now think about it it's quite obvious where the `user` value comes from, but for some reason, I needed an example to connect the dots. Maybe it would still help to add this to the doc, e.g.

```
When you run the following query then `resolve_user` is called to retrieve the user, 
which is passed in as the `obj` argument of `resolve_username`:

query {
  user {
    username
  }
}
```

**Comment by makeroftools** [comment]
The problem with open source.. in my 20 years being self taught and voice for its advocation.. is the lack of responsibility to adequately document.. as much as I respect the leaders and cherish the project and it's community.. So much time is wasted @rafalp
