### ISSUE TITLE
Accessing info.context["request"].user leads to AuthenticationMiddleware exception in subscription resolver.

### ISSUE THREAD

**Issue by erikdewildt** [mirumee/ariadne#472]
Hi,

I've build a GraphQL API setup using Ariadne and Django Channels as described in the documentation.

In the subscription resolver function I want to access the user to check for permissions. However when I try to access the user attribute of info.context["request"] I get an exception:
 
> Traceback (most recent call last):
>   File "/Users/erik/.virtualenvs/firewallautomation/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-8-cd52487b0e1d>", line 1, in <module>
>     info.context["request"].user
>   File "/Users/erik/.virtualenvs/firewallautomation/lib/python3.9/site-packages/starlette/requests.py", line 146, in user
>     assert (
> AssertionError: AuthenticationMiddleware must be installed to access request.user

I'm using the `ariadne-jwt` package for authentication, this works fine for normal queries but can not be used for subscriptions as it seems to require access to the user property. [https://github.com/Usama0121/ariadne-jwt/issues/6](url)

Any advice would be appreciated!

Thanks,
Regard,

Erik

**Comment by rafalp** [comment]
Hi!

There are two issues here:

Header based approach will not work GraphQL subscriptions. This is because those are done over the websocket, and websockets don't support custom HTTP headers. Connection params access is not supported in the core, but can be manually hacked in via implementing custom `GraphQL` ASGI app extending the `ariadne.asgi.GraphQL`. [You can use existing PR to Ariadne for inspiration](https://github.com/mirumee/ariadne/pull/355/files).

`request` object used by Ariadne is not Django's `HTTPRequest` instance, but instead `Request` from `Starlette`. This is because ASGI stack exists above the Django's HTTP stack which normally handles creation of `HTTPRequest` and execution of Django's middlewares. This means you will need to implement custom ASGI middleware populating `scope["user"]` with anonymous user instance.

**Comment by erikdewildt** [comment]
Hi,

Thanks for your answer. I understand the issue, going to have a look into the solution you propose.

Regards,
Erik
