### ISSUE TITLE
Handle safe method HTTP OPTIONS

### ISSUE THREAD

**Issue by accredited-unicorn** [mirumee/ariadne#664]
GraphQL clients may need to know whether Ariadne is processing QUERY / MUTATION using either of HTTP GET or HTTP POST. But any HTTP request that is **not** using the POST method currently throws an HTTP 405 Method Not Allowed (unless _introspection_ is turned on).

Can you please update Ariadne to safely respond to HTTP OPTIONS such that it informs any inquiring client that only HTTP POST methods are to be used when processing either of QUERY or MUTATION?

**Comment by accredited-unicorn** [comment]
Without any deep knowledge of Ariadne, could it be possible to resolve this issue with only [the following code](https://github.com/mirumee/ariadne/blob/f18afbefd6b6aec7f3b56b775ea906dcca246802/ariadne/asgi.py#L150) change?

```python
async def handle_http(self, scope: Scope, receive: Receive, send: Send):
    request = Request(scope=scope, receive=receive)
    if request.method == "GET" and self.introspection:
        # only render playground when introspection is enabled
        response = await self.render_playground(request)
    elif request.method == "POST":
        response = await self.graphql_http_server(request)
    elif request.method == "OPTIONS":
        allowed_methods = ["OPTIONS", "POST"]
        if self.introspection: allowed_methods.append("GET")
        response = JSONResponse(headers={"Allow": allowed_methods})
    else:
        response = Response(status_code=405)
    await response(scope, receive, send)
```

**Comment by rafalp** [comment]
We don't currently support query execution over `GET`, only via `POST`.

We can fix `OPTIONS` to report that `GET` is supported if introspection is enabled, but this will only mean that you can run HTTP GET request to retrieve the GraphQL Playground. GraphQL clients will still fail for `GET` queries because response will fail either the response type (HTTP vs JSON) or because they attempted to parse HTML as JSON, which is what I've already seen some clients in the wild do, producing the "`< is not expected...`" error message.

We also have issue for executing queries over `GET`, but that one didn't gain much support since it was opened: #123

**Comment by accredited-unicorn** [comment]
I might be missing something in the Ariadne codebase. I cannot find handling of the `OPTIONS` method at all. Your point is well taken though- responding to that particular method should only include `OPTIONS` and `POST` in the `Allow` header.

I'm currently working around this problem by mounting Ariadne onto FastAPI, and implementing a response to `OPTIONS` in the latter. Other than this work around, Ariadne currently suits all my back-end needs; and I'd rather not pay the various costs associated with mounting.

I also think it is general good practice to keep to the [`HTTP` ref spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Allow), which states _"The `Allow` header must be sent if the server responds with a 405 Method Not Allowed status code to indicate which request methods can be used."._
