### ISSUE TITLE
Graphql query resolution gets very slow with middlewares.

### ISSUE THREAD

**Issue by gghildyal** [mirumee/ariadne#708]
While debugging performance issues with queries that return a long list, I found that my middleware was causing a lot of slowness. At which point I reduced my middleware to a bare-bones middleware like this

```
class LoginRequiredMiddleware(object):
    """A middleware that raises a consistent error for unauthenticated users."""

    @staticmethod
    async def resolve(  # type: ignore
        resolver: Resolver,
        parent: Any,
        info: GraphQLResolveInfo,
        **kwargs,
    ):
            result = resolver(parent, info, **kwargs)
            if isawaitable(result):
                result = await result
            return result
```

With this middleware, a nested query below takes ~27 seconds. Without it, it takes 5 seconds!

```
query {
  operators {
      lines {
          lineId
          servicePatterns {
            stops {
              stopId
            }
          }
      }
    }
  }
```
can return a long list of service patterns and stops (~10,000 items).

Am I just paying the price of that extra function call? Or because I am awaiting every resolver in the middleware?

**Comment by kissgyorgy** [comment]
We ran into the same issue, we didn't know (it's not intuitive) that graphql-core changes EVERY single resolver to your middleware, so even if you have a simple attribute or dict value lookup, the middleware will run as many times as many properties your object has. In our case, more than 20,000 extra coroutines have been created, which slowed everything down by 4-5x.

For authentication, we went down one level abstraction and wrote a Starlette middleware, so every query is authenticated only once. If you need any middleware functionality, I suggest doing the same and using Starlette middleware instead of graphql-core middlewares.

**Comment by rafalp** [comment]
ASGI middleware is the way to go for auth. GraphQL middlewares are more often a trap than useful solution.

**Comment by rafalp** [comment]
I'll label this as doc. We should bring this up as a warning.

**Comment by rafalp** [comment]
I'll add section about performance impact of middlewares to our docs. Thanks for bringing this up!

**Comment by dacevedo12** [comment]
Can confirm, middlewares and extensions are very taxing even on simple tasks

@rafalp How should one go if the intent is to cover every single resolver for something like: https://github.com/mirumee/ariadne/issues/649?

**Comment by kissgyorgy** [comment]
We measured the impact of turning simple functions into coroutines and the slowdown is 100x (😱) so I don't think you can use this "middleware every resolver" without a serious performance hit.
